server:
  port: 10010

spring:
  # 数据库配置
  datasource:
    username: abao
    password: abao
    url: jdbc:mysql://localhost:3306/abao?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
  # mongo配置
  data:
    mongodb:
      host: localhost
      port: 27017
  # redis配置
  redis:
    host: localhost
    port: 6379
